version: '3.3'
services:
    simplehtmlnginx:
        image: .
        container_name: simplehtmlnginx
        restart: unless-stopped
        ports: 
            - "38666:80"
            - "38667:443"